#! /usr/bin/env python3

# Core modules
import sys

# Third party modules
import pymongo


hostname = sys.argv[1]
try:
    port = sys.argv[2]
except IndexError:
    port = '27017'

client = pymongo.MongoClient(
    hostname, int(port),
    serverSelectionTimeoutMS=1000
)
time_spent = 0

while True:
    try:
        print(
            (
                '- Trying to connect to {hostname}:{port} '
                'after {time_spent} seconds'
            ).format(**locals())
        )
        client.server_info()

        print('- Database available')
        sys.exit(0)
    except pymongo.errors.ServerSelectionTimeoutError:
        time_spent += 1
