#! /usr/bin/env python3

# Core modules
import sys
import time

# Third party modules
import psycopg2


hostname = sys.argv[1]
try:
    port = sys.argv[2]
except IndexError:
    port = '5432'

time_spent = 0

while True:
    try:
        print(
            (
                '- Trying to connect to {hostname}:{port} '
                'after {time_spent} seconds'
            ).format(**locals())
        )
        psycopg2.connect(
            (
                "host='{hostname}' port='{port}' user='postgres'"
            ).format(**locals())
        )

        print('- Database available')
        sys.exit(0)
    except psycopg2.OperationalError:
        time.sleep(1)
        time_spent += 1
